In [1]:
import pickle
import numpy as np
import math

# Fix error with TF and Keras
import tensorflow as tf
tf.python.control_flow_ops = tf

print('Modules loaded.')

Modules loaded.


In [2]:
from keras.models import Sequential 
from keras.datasets import cifar10
(X_train, y_train), (X_test, y_test) = cifar10.load_data()

Using TensorFlow backend.


In [3]:
# Check if input is normalized
print(np.min(X_train), np.max(X_train))

0 255


In [4]:
# TODO: Normalize the data features to the variable X_normalized
def normalize_grayscale(image_data):
    a = -0.5
    b = 0.5
    grayscale_min = 0
    grayscale_max = 255
    return a + ( ( (image_data - grayscale_min)*(b - a) )/( grayscale_max - grayscale_min ) )

X_train_norm= normalize_grayscale(X_train)
X_test_norm= normalize_grayscale(X_test)

print(np.min(X_train_norm), np.max(X_train_norm))

-0.5 0.5


In [10]:
# TODO: One Hot encode the labels to the variable y_one_hot
from sklearn.preprocessing import LabelBinarizer
label_binarizer = LabelBinarizer()
y_train_one_hot = label_binarizer.fit_transform(y_train)
y_test_one_hot = label_binarizer.fit_transform(y_test)
print(y_train_one_hot[:10])

[[0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 1 0 0 0 0 0 0]]


In [9]:
# TODO: Build a model
from keras.models import Sequential
from keras.models import Sequential
from keras.layers.core import Dense, Activation, Flatten, Dropout
from keras.layers.convolutional import Convolution2D
from keras.layers.pooling import MaxPooling2D

model = Sequential()
model.add(Convolution2D(32, 3, 3, input_shape=(32, 32, 3)))
model.add(MaxPooling2D((2, 2)))
model.add(Dropout(0.5))
model.add(Activation('relu'))
model.add(Convolution2D(32, 3, 3, input_shape=(32, 32, 3)))
model.add(MaxPooling2D((2, 2)))
model.add(Dropout(0.5))
model.add(Activation('relu'))
model.add(Flatten())
model.add(Dense(128))
model.add(Activation('relu'))
model.add(Dense(10))
model.add(Activation('softmax'))

# TODO: Compile and train the model
model.compile('adam', 'categorical_crossentropy', ['accuracy'])
history = model.fit(X_train_norm, y_train_one_hot, nb_epoch=10, validation_split=0.2)

Train on 40000 samples, validate on 10000 samples
Epoch 1/10
40000/40000 [==============================] - 16s - loss: 1.5973 - acc: 0.4201 - val_loss: 1.3271 - val_acc: 0.5338
Epoch 2/10
40000/40000 [==============================] - 15s - loss: 1.3301 - acc: 0.5199 - val_loss: 1.2124 - val_acc: 0.5734
Epoch 3/10
40000/40000 [==============================] - 15s - loss: 1.2338 - acc: 0.5594 - val_loss: 1.1190 - val_acc: 0.6143
Epoch 4/10
40000/40000 [==============================] - 15s - loss: 1.1632 - acc: 0.5859 - val_loss: 1.0489 - val_acc: 0.6389
Epoch 5/10
40000/40000 [==============================] - 15s - loss: 1.1108 - acc: 0.6076 - val_loss: 1.0002 - val_acc: 0.6601
Epoch 6/10
40000/40000 [==============================] - 15s - loss: 1.0660 - acc: 0.6227 - val_loss: 0.9695 - val_acc: 0.6664
Epoch 7/10
40000/40000 [==============================] - 15s - loss: 1.0302 - acc: 0.6353 - val_loss: 0.9877 - val_acc: 0.6648
Epoch 8/10
40000/40000 [==============================

In [11]:
# TODO: Evaluate model on test data
metrics = model.evaluate(X_test_norm, y_test_one_hot)
for metric_i in range(len(model.metrics_names)):
    metric_name = model.metrics_names[metric_i]
    metric_value = metrics[metric_i]
    print('{}: {}'.format(metric_name, metric_value))

 9952/10000 [============================>.] - ETA: 0sloss: 0.9002282526016235
acc: 0.691
